### ISSUE TITLE
pg_dump: error: query failed: ERROR:  out of shared memory

### ISSUE THREAD

**Issue by prensgold** [vitabaks/pgbackrest_auto#11]
Hi Vitaliy,

I am getting the following error in the data validation step.

>.
>.
>.
>.
>2023-03-08 08:58:11 INFO: Start data validation for database bkm_express
>2023-03-08 08:58:11 INFO:   starting pg_dump -p 5432 -h 127.0.0.1 -d bkm_express >> /dev/null
>pg_dump: error: query failed: ERROR:  out of shared memory
>HINT:  You might need to increase max_locks_per_transaction.
>pg_dump: error: query was: LOCK TABLE bkmexpress.virtual_pos_log IN ACCESS SHARE MODE
>2023-03-08 08:58:25 ERROR: Data validation in the database bkm_express - Failed
>[postgres@dbtest01 data]$ cat postgresql.conf
>listen_addresses = '*'
>port = 5432
>max_connections = 500
>max_worker_processes = 24
>max_prepared_transactions = 0
>max_locks_per_transaction = 64
>[postgres@dbtest01 data]$ 

I was able to solve it by increasing the max_locks_per_transaction value.
Default values are written to the conf file.

I took the following document as an example for optimization.
https://cloud.google.com/sql/docs/postgres/optimize-high-memory-usage

I used the following query for the minimum value.
SELECT ((SELECT count(*) as object_count
         FROM pg_catalog.pg_class c
         LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         WHERE c.relkind IN ('r', 'v', 'i', 'S', 's')) /
        (SELECT current_setting('max_connections')::float))+1 as MIN_max_locks_per_transaction_VALUE;

How can we optimize this dynamically in your software?

**Comment by vitabaks** [comment]
We get the value from pg_control https://github.com/vitabaks/pgbackrest_auto/blob/master/pgbackrest_auto#L643

You can increase the value of `max_locks_per_transaction` on the source database and we will use the new value at the next restore from the backup.
