### ISSUE TITLE
pgbackrest server

### ISSUE THREAD

**Issue by BabaTataKaka** [vitabaks/pgbackrest_auto#19]
Looks like the script must run a postgres server that has pgbackest installed on it. So the script would obliviously not work with a dedicated pgbackrest server. Is there any plan to make it work with a dedicated pgbackrest server? If not, what would be the required change? I would like to use the script for backup validation and restore validation (validation only, no restore). I have a dedicated pgbackrest server.

Thanks

**Comment by vitabaks** [comment]
I use it on a dedicated server. What is your problem?

**Comment by BabaTataKaka** [comment]
When I run a backup cronjob (with dbcheck) on the pgbackrest server it complain that there is no "usr/lib/postgresql/16/bin" folder. Therefore,  I'm assuming it has to run on the postgres server.  I'm passing the correct postgres version when calling the script.

**Comment by vitabaks** [comment]
You are restoring the database and running it for verification, so you need to install the PostgreSQL packages.

**Comment by BabaTataKaka** [comment]
Ok thanks. It's working now. I know it sound obvious, but may be it should be specified in the requirements section in the doc? Also, if I understand correctly, restoring on the pgbackrest server is part of the verification process?

**Comment by vitabaks** [comment]
Feel free to suggest a PR

**Comment by BabaTataKaka** [comment]
In your example when running a cronjob to generate a backup, you don't specify --norestore. Is there any benefit of restoring after each backup created?
